Repository team-winey/Winey-Server, pull requests merged in 2023-07, with the labels that each got.

#4 [Feat] domain 작성
  src/main/java/org/winey/server/domain/goal/Goal.java
  src/main/java/org/winey/server/domain/recommend/Recommend.java
  src/main/java/org/winey/server/domain/user/User.java
  src/main/java/org/winey/server/domain/user/UserLevel.java
Labels: Sunny

#8 [Feat] getRecommend
  src/main/java/org/winey/server/common/advice/ControllerExceptionAdvice.java
  src/main/java/org/winey/server/controller/RecommendController.java
  src/main/java/org/winey/server/controller/response/PageResponseDto.java
  src/main/java/org/winey/server/controller/response/recommend/RecommendListResponseDto.java
  src/main/java/org/winey/server/controller/response/recommend/RecommendResponseDto.java
  src/main/java/org/winey/server/controller/response/recommend/RecommendResponseUserDto.java
  src/main/java/org/winey/server/domain/recommend/Recommend.java
  src/main/java/org/winey/server/exception/Error.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/RecommendRepository.java
  src/main/java/org/winey/server/infrastructure/UserRepository.java
  src/main/java/org/winey/server/service/RecommendService.java
Labels: Sunny

#10 [Feat] createGoal
  src/main/java/org/winey/server/ServerApplication.java
  src/main/java/org/winey/server/controller/GoalController.java
  src/main/java/org/winey/server/controller/request/goal/GoalRequestCreateDto.java
  src/main/java/org/winey/server/controller/response/goal/GoalResponseCreateDto.java
  src/main/java/org/winey/server/domain/goal/Goal.java
  src/main/java/org/winey/server/domain/user/User.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/GoalRepository.java
  src/main/java/org/winey/server/infrastructure/RecommendRepository.java
  src/main/java/org/winey/server/infrastructure/UserRepository.java
  src/main/java/org/winey/server/service/GoalService.java
Labels: Sunny

#16 Feat/#12 피드 삭제하기 구현
  src/main/java/org/winey/server/ServerApplication.java
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/request/CreateFeedRequestDto.java
  src/main/java/org/winey/server/controller/response/feed/CreateFeedResponseDto.java
  src/main/java/org/winey/server/domain/feed/Feed.java
  src/main/java/org/winey/server/domain/goal/Goal.java
  src/main/java/org/winey/server/domain/user/User.java
  src/main/java/org/winey/server/exception/Error.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/exception/model/ForbiddenException.java
  src/main/java/org/winey/server/infrastructure/FeedRepository.java
  src/main/java/org/winey/server/infrastructure/GoalRepository.java
  src/main/java/org/winey/server/service/FeedService.java
Labels: Feat, refactor

#17 [Feat] getUser
  src/main/java/org/winey/server/controller/UserController.java
  src/main/java/org/winey/server/controller/response/PageResponseDto.java
  src/main/java/org/winey/server/controller/response/user/UserResponseDto.java
  src/main/java/org/winey/server/controller/response/user/UserResponseGoalDto.java
  src/main/java/org/winey/server/controller/response/user/UserResponseUserDto.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/service/UserService.java
Labels: Sunny

#22 Feat/#19
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/response/feed/GetAllFeedResponseDto.java
  src/main/java/org/winey/server/controller/response/feed/GetFeedResponseDto.java
  src/main/java/org/winey/server/controller/response/feed/GetWriterResponseDto.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/FeedLikeRepository.java
  src/main/java/org/winey/server/infrastructure/FeedRepository.java
  src/main/java/org/winey/server/service/FeedService.java
Labels: soohyun, Feat

#25 Bug/#24
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/external/client/aws/S3Service.java
Labels: bug, soohyun

#27 #23 [Feat] getMyFeed 구현하기
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/FeedRepository.java
  src/main/java/org/winey/server/service/FeedService.java
Labels: soohyun, Feat

#28 [Fix] 추천 위니 변경사항
  src/main/java/org/winey/server/controller/response/feed/GetAllFeedResponseDto.java
  src/main/java/org/winey/server/controller/response/recommend/RecommendListResponseDto.java
  src/main/java/org/winey/server/controller/response/recommend/RecommendResponseDto.java
  src/main/java/org/winey/server/controller/response/recommend/RecommendResponseUserDto.java
  src/main/java/org/winey/server/domain/recommend/Recommend.java
  src/main/java/org/winey/server/service/RecommendService.java
Labels: Sunny

#33 [Feat] 피드 좋아요 기능
  src/main/java/org/winey/server/common/advice/ControllerExceptionAdvice.java
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/FeedLikeController.java
  src/main/java/org/winey/server/controller/RecommendController.java
  src/main/java/org/winey/server/controller/request/feedLike/CreateFeedLikeRequestDto.java
  src/main/java/org/winey/server/controller/response/feedLike/CreateFeedLikeResponseDto.java
  src/main/java/org/winey/server/domain/feed/FeedLike.java
  src/main/java/org/winey/server/exception/Error.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/FeedLikeRepository.java
  src/main/java/org/winey/server/service/FeedLikeService.java
  src/main/java/org/winey/server/service/FeedService.java
  src/main/java/org/winey/server/service/RecommendService.java
Labels: Sunny

#37 Feat/#29 클라이언트를 위한 Swagger 작성
  src/main/java/org/winey/server/config/swagger/SwaggerConfig.java
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/FeedLikeController.java
  src/main/java/org/winey/server/controller/GoalController.java
  src/main/java/org/winey/server/controller/RecommendController.java
  src/main/java/org/winey/server/controller/UserController.java
Labels: soohyun, Feat

#38 [Feat] 슬랙 500 알림
  build.gradle
  src/main/java/org/winey/server/common/advice/ControllerExceptionAdvice.java
  src/main/java/org/winey/server/controller/SlackTestController.java
  src/main/java/org/winey/server/slack/SlackApi.java
Labels: Sunny

#42 [Fix] 좋아요 수 Long 타입으로 변경
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/FeedLikeController.java
  src/main/java/org/winey/server/controller/RecommendController.java
  src/main/java/org/winey/server/controller/response/feed/GetFeedResponseDto.java
  src/main/java/org/winey/server/controller/response/feedLike/CreateFeedLikeResponseDto.java
  src/main/java/org/winey/server/service/FeedLikeService.java
  src/main/java/org/winey/server/service/FeedService.java
Labels: Sunny

#43 [Fix] 좋아요 수 Long 타입으로 변경 배포
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/FeedLikeController.java
  src/main/java/org/winey/server/controller/RecommendController.java
  src/main/java/org/winey/server/controller/response/feed/GetFeedResponseDto.java
  src/main/java/org/winey/server/controller/response/feedLike/CreateFeedLikeResponseDto.java
  src/main/java/org/winey/server/service/FeedLikeService.java
  src/main/java/org/winey/server/service/FeedService.java
Labels: Sunny

#46 [Fix] 금액 response 할 때 콤마 표기 추가
  src/main/java/org/winey/server/service/RecommendService.java
Labels: Sunny

#52 Refactor/#51
  src/main/java/org/winey/server/controller/response/user/UserResponseGoalDto.java
  src/main/java/org/winey/server/service/UserService.java
Labels: soohyun, refactor

#55 [Fix] 추천 위니 페이지네이션 수 바꾸기, d-day 계산 수정
  src/main/java/org/winey/server/service/FeedService.java
  src/main/java/org/winey/server/service/RecommendService.java
  src/main/java/org/winey/server/service/UserService.java
Labels: Sunny

#60 Bug/#59
  src/main/java/org/winey/server/service/FeedService.java
  src/main/java/org/winey/server/service/RecommendService.java
  src/main/java/org/winey/server/service/UserService.java
Labels: bug, soohyun

#61 main에 dday 로직수정 merge
  src/main/java/org/winey/server/service/FeedService.java
  src/main/java/org/winey/server/service/RecommendService.java
  src/main/java/org/winey/server/service/UserService.java
Labels: bug, soohyun

#63 [Feat] FeedLike - Feed cascade 추가
  src/main/java/org/winey/server/domain/feed/Feed.java
  src/main/java/org/winey/server/domain/feed/FeedLike.java
Labels: Sunny

#73 [Fix] 추천 위니 pagination 한 페이지당 20으로 업데이트
  src/main/java/org/winey/server/service/RecommendService.java
Labels: Sunny

#76 [Fix] responseDto NON_NULL 제거
  src/main/java/org/winey/server/controller/response/recommend/RecommendResponseDto.java
Labels: Sunny

#79 [Feat] HttpRequestMethodNotSupportedException 예외 처리
  src/main/java/org/winey/server/common/advice/ControllerExceptionAdvice.java
  src/main/java/org/winey/server/exception/Error.java
Labels: Sunny

#82 [Feat] 위니피드, 목표 제한
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/request/CreateFeedRequestDto.java
  src/main/java/org/winey/server/controller/request/goal/GoalRequestCreateDto.java
  src/main/java/org/winey/server/exception/Error.java
Labels: Sunny

#88 [Feat] 소셜 로그인 세팅 및 애플 로그인 구현
  build.gradle
  src/main/java/org/winey/server/ServerApplication.java
  src/main/java/org/winey/server/config/jwt/JwtService.java
  src/main/java/org/winey/server/controller/AuthController.java
  src/main/java/org/winey/server/controller/request/auth/SignInRequestDto.java
  src/main/java/org/winey/server/controller/response/auth/SignInResponseDto.java
  src/main/java/org/winey/server/domain/user/SocialType.java
  src/main/java/org/winey/server/domain/user/User.java
  src/main/java/org/winey/server/exception/Error.java
  src/main/java/org/winey/server/infrastructure/UserRepository.java
  src/main/java/org/winey/server/service/auth/AuthService.java
  src/main/java/org/winey/server/service/auth/apple/AppleSignInService.java
  src/main/java/org/winey/server/service/auth/apple/feign/AppleApiClient.java
  src/main/java/org/winey/server/service/auth/apple/response/ApplePublicKey.java
  src/main/java/org/winey/server/service/auth/apple/response/ApplePublicKeys.java
  src/main/java/org/winey/server/service/auth/apple/verify/AppleJwtParser.java
  src/main/java/org/winey/server/service/auth/apple/verify/EncryptUtils.java
  src/main/java/org/winey/server/service/auth/apple/verify/PublicKeyGenerator.java
Labels: Sunny
