Repository team-winey/Winey-Server, pull requests merged in 2023-09, with the labels that each got.

#158 Feat/#157 정해진 시간 지나면 자동으로 알림 삭제
  src/main/java/org/winey/server/infrastructure/NotiRepository.java
  src/main/java/org/winey/server/service/NotiService.java
Labels: soohyun, Feat

#161 [Fix] 피드 삭제 관련 오류
  src/main/java/org/winey/server/domain/feed/Feed.java
  src/main/java/org/winey/server/domain/goal/Goal.java
  src/main/java/org/winey/server/service/FeedService.java
Labels: Sunny

#165 Bug/#164 중복 엔티티 발생 버그 해결시도
  src/main/java/org/winey/server/service/NotiService.java
Labels: bug, soohyun

#170 Feat/#169 피드 삭제 시 id 값 반환
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/response/feed/DeleteFeedResponseDto.java
  src/main/java/org/winey/server/service/auth/AuthService.java
Labels: soohyun, Feat
