Repository team-winey/Winey-Server, pull requests merged in 2023-08, with the labels that each got.

#91 [Feat] 유저 인증 애너테이션, 토큰 재발급, 로그아웃
  src/main/java/org/winey/server/config/WebConfig.java
  src/main/java/org/winey/server/config/jwt/JwtService.java
  src/main/java/org/winey/server/config/resolver/UserId.java
  src/main/java/org/winey/server/config/resolver/UserIdResolver.java
  src/main/java/org/winey/server/controller/AuthController.java
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/FeedLikeController.java
  src/main/java/org/winey/server/controller/GoalController.java
  src/main/java/org/winey/server/controller/UserController.java
  src/main/java/org/winey/server/controller/response/auth/TokenResponseDto.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/UserRepository.java
  src/main/java/org/winey/server/service/auth/AuthService.java
Labels: Sunny

#93 Feat/#31
  build.gradle
  src/main/java/org/winey/server/common/advice/ControllerExceptionAdvice.java
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/response/auth/SignInResponseDto.java
  src/main/java/org/winey/server/domain/user/SocialType.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/service/auth/AuthService.java
  src/main/java/org/winey/server/service/auth/kakao/KakaoSignInService.java
  src/main/java/org/winey/server/service/auth/kakao/dto/response/KakaoAccessTokenResponse.java
  src/main/java/org/winey/server/service/auth/kakao/dto/response/KakaoAccount.java
  src/main/java/org/winey/server/service/auth/kakao/dto/response/KakaoUserProfile.java
  src/main/java/org/winey/server/service/auth/kakao/dto/response/KakaoUserResponse.java
Labels: Feat

#96 [Feat] 닉네임 수정 API
  src/main/java/org/winey/server/controller/UserController.java
  src/main/java/org/winey/server/controller/request/UpdateUserNicknameDto.java
  src/main/java/org/winey/server/domain/user/User.java
  src/main/java/org/winey/server/exception/Error.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/UserRepository.java
  src/main/java/org/winey/server/service/UserService.java
Labels: Sunny

#98 Feat/#94
  src/main/java/org/winey/server/controller/AuthController.java
  src/main/java/org/winey/server/domain/user/User.java
  src/main/java/org/winey/server/exception/Error.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/exception/model/UnprocessableEntityException.java
  src/main/java/org/winey/server/infrastructure/GoalRepository.java
  src/main/java/org/winey/server/infrastructure/UserRepository.java
  src/main/java/org/winey/server/service/auth/AuthService.java
Labels: soohyun, Feat

#101 Feat/#100
  src/main/java/org/winey/server/controller/CommentController.java
  src/main/java/org/winey/server/controller/request/comment/CreateCommentRequestDto.java
  src/main/java/org/winey/server/controller/response/comment/CreateCommentResponseDto.java
  src/main/java/org/winey/server/domain/comment/Comment.java
  src/main/java/org/winey/server/domain/feed/Feed.java
  src/main/java/org/winey/server/domain/user/User.java
  src/main/java/org/winey/server/exception/Error.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/CommentRepository.java
  src/main/java/org/winey/server/service/CommentService.java
  src/main/java/org/winey/server/service/auth/AuthService.java
Labels: soohyun, Feat

#104 댓글 merge to main
  src/main/java/org/winey/server/controller/CommentController.java
  src/main/java/org/winey/server/controller/request/comment/CreateCommentRequestDto.java
  src/main/java/org/winey/server/controller/response/comment/CreateCommentResponseDto.java
  src/main/java/org/winey/server/domain/comment/Comment.java
  src/main/java/org/winey/server/domain/feed/Feed.java
  src/main/java/org/winey/server/domain/user/User.java
  src/main/java/org/winey/server/exception/Error.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/CommentRepository.java
  src/main/java/org/winey/server/service/CommentService.java
  src/main/java/org/winey/server/service/auth/AuthService.java
Labels: soohyun, Feat

#105 [Fix] 변경사항 다시 적용
  src/main/java/org/winey/server/controller/response/comment/CreateCommentResponseDto.java
  src/main/java/org/winey/server/service/CommentService.java
Labels: bug, soohyun

#107 Feat/#102
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/response/comment/GetCommentResponseDto.java
  src/main/java/org/winey/server/controller/response/feed/GetFeedDetailResponseDto.java
  src/main/java/org/winey/server/controller/response/feed/GetFeedResponseDto.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/CommentRepository.java
  src/main/java/org/winey/server/service/FeedService.java
Labels: soohyun, Feat

#108 merge to main
  src/main/java/org/winey/server/controller/FeedController.java
  src/main/java/org/winey/server/controller/response/comment/GetCommentResponseDto.java
  src/main/java/org/winey/server/controller/response/feed/GetFeedDetailResponseDto.java
  src/main/java/org/winey/server/controller/response/feed/GetFeedResponseDto.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/CommentRepository.java
  src/main/java/org/winey/server/service/FeedService.java
Labels: Feat

#117 Feat/#103
  src/main/java/org/winey/server/ServerApplication.java
  src/main/java/org/winey/server/controller/NotiController.java
  src/main/java/org/winey/server/controller/response/auth/SignInResponseDto.java
  src/main/java/org/winey/server/controller/response/comment/GetCommentResponseDto.java
  src/main/java/org/winey/server/controller/response/notification/GetAllNotiResponseDto.java
  src/main/java/org/winey/server/controller/response/notification/GetNotiResponseDto.java
  src/main/java/org/winey/server/domain/feed/Feed.java
  src/main/java/org/winey/server/domain/notification/NotiType.java
  src/main/java/org/winey/server/domain/notification/Notification.java
  src/main/java/org/winey/server/domain/user/User.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/GoalRepository.java
  src/main/java/org/winey/server/infrastructure/NotiRepository.java
  src/main/java/org/winey/server/service/CommentService.java
  src/main/java/org/winey/server/service/FeedLikeService.java
  src/main/java/org/winey/server/service/FeedService.java
  src/main/java/org/winey/server/service/NotiService.java
  src/main/java/org/winey/server/service/auth/AuthService.java
Labels: soohyun, Feat, refactor

#120 [Feat] 알림 삭제 기능 추가 / 알림 미확인 여부 API
  src/main/java/org/winey/server/controller/NotiController.java
  src/main/java/org/winey/server/controller/response/feed/GetFeedResponseDto.java
  src/main/java/org/winey/server/controller/response/notification/GetNotiResponseDto.java
  src/main/java/org/winey/server/domain/notification/Notification.java
  src/main/java/org/winey/server/exception/Success.java
  src/main/java/org/winey/server/infrastructure/CommentRepository.java
  src/main/java/org/winey/server/infrastructure/FeedLikeRepository.java
  src/main/java/org/winey/server/infrastructure/NotiRepository.java
  src/main/java/org/winey/server/service/CommentService.java
  src/main/java/org/winey/server/service/FeedLikeService.java
  src/main/java/org/winey/server/service/FeedService.java
  src/main/java/org/winey/server/service/NotiService.java
  src/main/java/org/winey/server/service/auth/AuthService.java
  src/main/java/org/winey/server/util/dummy.sql
  src/main/java/org/winey/server/util/recommend.sql
  src/main/java/org/winey/server/util/settingDemo.sql
Labels: Sunny

#123 [Fix] timeAgo 시간 추가
  src/main/java/org/winey/server/service/FeedService.java
  src/main/java/org/winey/server/service/NotiService.java
Labels: Sunny

#125 Refactor/#118
  src/main/java/org/winey/server/controller/NotiController.java
  src/main/java/org/winey/server/infrastructure/CommentRepository.java
  src/main/java/org/winey/server/service/FeedService.java
Labels: soohyun, refactor

#126 merge to main
  src/main/java/org/winey/server/controller/NotiController.java
  src/main/java/org/winey/server/infrastructure/CommentRepository.java
  src/main/java/org/winey/server/service/FeedService.java
Labels: soohyun, refactor

#128 Refactor/#127
  src/main/java/org/winey/server/controller/CommentController.java
  src/main/java/org/winey/server/controller/response/comment/CommentResponseDto.java
  src/main/java/org/winey/server/controller/response/comment/CreateCommentResponseDto.java
  src/main/java/org/winey/server/controller/response/feed/GetFeedDetailResponseDto.java
  src/main/java/org/winey/server/domain/user/User.java
  src/main/java/org/winey/server/service/CommentService.java
  src/main/java/org/winey/server/service/FeedService.java
  src/main/java/org/winey/server/service/auth/AuthService.java
Labels: soohyun, refactor

#129 merge to main
  src/main/java/org/winey/server/controller/CommentController.java
  src/main/java/org/winey/server/controller/response/comment/CommentResponseDto.java
  src/main/java/org/winey/server/controller/response/comment/CreateCommentResponseDto.java
  src/main/java/org/winey/server/controller/response/feed/GetFeedDetailResponseDto.java
  src/main/java/org/winey/server/domain/user/User.java
  src/main/java/org/winey/server/service/CommentService.java
  src/main/java/org/winey/server/service/FeedService.java
  src/main/java/org/winey/server/service/auth/AuthService.java
Labels: soohyun, refactor

#130 [Refactor] 댓글삭제시 댓글id 보내주기
  src/main/java/org/winey/server/controller/CommentController.java
  src/main/java/org/winey/server/controller/response/comment/DeleteCommentResponseDto.java
  src/main/java/org/winey/server/service/CommentService.java
Labels: soohyun, refactor

#134 Bug/#133
  src/main/java/org/winey/server/service/FeedLikeService.java
  src/main/java/org/winey/server/service/auth/AuthService.java
Labels: bug, soohyun

#148 [Feat] 목표 달성시 isOver -> true, 만료된 추천 위니 삭제
  src/main/java/org/winey/server/service/UserService.java
  src/main/java/org/winey/server/util/recommend.sql
Labels: Sunny

#146 Bug/#145
  src/main/java/org/winey/server/domain/comment/Comment.java
  src/main/java/org/winey/server/domain/notification/Notification.java
  src/main/java/org/winey/server/infrastructure/NotiRepository.java
  src/main/java/org/winey/server/service/UserService.java
Labels: bug, soohyun

#153 merge to main
  src/main/java/org/winey/server/domain/goal/Goal.java
  src/main/java/org/winey/server/service/FeedService.java
Labels: soohyun, refactor

#155 [Fix] 마이페이지 수정
  src/main/java/org/winey/server/service/FeedService.java
  src/main/java/org/winey/server/service/UserService.java
Labels: Sunny
