Repository team-winey/Winey-Server, pull requests merged in 2024-02, with the labels that each got.

#225 [Fix] 마이페이지 API 구조 변경
  src/main/java/org/winey/server/controller/response/user/UserResponseDto.java
Labels: bug, kwan

#229 [Feat] 누적 위니 null일 경우 0 반환
  src/main/java/org/winey/server/service/UserService.java
Labels: Sunny, Feat

#231 [Refactor] user 페이지에 남은 금액 남은 횟수 추가
  src/main/java/org/winey/server/controller/response/user/UserResponseDto.java
  src/main/java/org/winey/server/service/UserService.java
Labels: soohyun, refactor

#233 [Refactor]#232 절약 누적횟수 추가
  src/main/java/org/winey/server/controller/response/user/UserResponseDto.java
  src/main/java/org/winey/server/service/UserService.java
Labels: soohyun, refactor
